# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Generate minified versions

on:
  push:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8 
    - name: Update files
      env:
        PYTHONPATH: ${{ github.workspace }}
      shell: python
      run: |
        import versiondb
        list = versiondb.VersionList('.')
        list.save_minified('armeabi-v7a')
        list.save_minified('x86')
        list.save_minified('arm64-v8a')
        list.save_minified('x86_64')
    - name: Update git
      run: |
        git add .
        git commit -m "Update minified json's"
        git push
